services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./web/src:/app/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - APP_CONFIG_PATH=.env
      - GIN_MODE=debug
      - PORT=8000
    volumes:
      - ./backend:/app
